name: flutter_btprinter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  barcode_widget: ^2.0.3
  cupertino_icons: ^1.0.2
  esc_pos_utils_plus: ^2.0.1+6
  flutter:
    sdk: flutter
  get: 4.6.5
  get_storage: ^2.0.3
  image: ^3.2.2
  print_bluetooth_thermal: ^1.0.5
  screenshot: ^1.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
